### ISSUE TITLE
"Pin" instead of "Member ID" used on some front-page tables

### ISSUE THREAD

**Issue by annabunches** [usgo/agagd#103]
## Summary of the Bug
The "Most Rated Games (Past 12 Months)" and "Most Tournaments (Past 12 Months)" tables on `https://agagd.usgo.org/` use an inconsistent term for the member ID column heading: "Pin" instead of "Member ID".

**Comment by vash3g** [comment]
Changed settings and updates files to present a standard "members id" in the top ten lists.
