### ISSUE TITLE
Chapter value can be "None", which provides a link to a broken page.

### ISSUE THREAD

**Issue by annabunches** [usgo/agagd#105]
## Summary of the Bug
Some users have their chapter set somehow to "None", which provides a link to a chapter page that doesn't exist.

## Steps to Reproduce the Behaviour
Visit https://agagd.usgo.org/search/?q=dahlin, and click the "None" link in the table.

## The Expected Behaviour
A member who isn't part of a chapter should have a non-hyperlinked emdash in the "chapter" column.

This probably also needs a validation check added to the database somewhere.

**Comment by vash3g** [comment]
Indicated user does belong to a chapter but chapter also contains a symbol. "GoClub@Google" seems to be causing an error in display. You can also see this on https://agagd.usgo.org/search/?q=schumacher.

**Comment by annabunches** [comment]
Did a stealth change happen that fixed this? Both of the example queries now show users with no chapter information.

**Comment by EarthSchlange** [comment]
The issue does look to be resolved. 

![image](https://user-images.githubusercontent.com/5054653/97345720-a5e62480-1847-11eb-8e28-9ecf16201ea3.png)
