### ISSUE TITLE
Provide a link to the member's chapter on their detail page

### ISSUE THREAD

**Issue by annabunches** [usgo/agagd#106]
## Is your feature request related to a problem?
Not specifically.

## Describe the feature you'd like to see on the AGAGD.
A "chapter" field on the user's player card, with the chapter name hyperlinked to the chapter detail page.

**Comment by EarthSchlange** [comment]
The feature request here ties into issue #93 were we are moving to depreciate chapter codes. We need to make sure any chapter url links created for this feature request tie into #93.
