### ISSUE TITLE
Updating the AGAGD to Python3.7+ Results in Breaking Changes with Apache2 and Mod WSGI 

### ISSUE THREAD

**Issue by EarthSchlange** [usgo/agagd#112]
## Summary of the Bug
Multiple breaking changes when moving from a Python2.7 virtualenv to Python3.7+. Breaks can include: 

* "member object" being displayed instead of members name on numerious pages, 
* /gamestats" results in a timeout error

## Steps to Reproduce the Behaviour
1. Update virtualenv in Apache2 to Python3.7 from Python2.7
2. Install libapache2-mod-wsgi-py3
3. Restart Apache

## The Expected Behaviour
AGAGD application to work as before when using Apache2  and mod-wsgi.

## Screenshots
![image](https://user-images.githubusercontent.com/5054653/90962741-27e05880-e467-11ea-8a8e-3d22ba0aa758.png)

## Notes
* Only Python3.7+ results in breaking changes
* Apache2 must have the AGAGD environmental variables set

**Comment by duckpunch** [comment]
> "member object" being displayed instead of members name on numerious pages,

This appears to be from `django-tables2`.

**Comment by EarthSchlange** [comment]
Resolved in #155.
