### ISSUE TITLE
Tournament Display page, redundant data

### ISSUE THREAD

**Issue by JonathanBresler** [usgo/agagd#20]
Each tournament display page shows the Tournament Description from the database for each game.  this is redundant.   example: http://test.agagd.usgo.org/tournaments/nova20121215/ last column of the display

**Comment by vash3g** [comment]
Referencing tables.py under Meta section of `class GameTable(tables.Table):`

Old code: `
        fields = ("game_date", "round", "pin_player_1",
                "pin_player_2", 'handicap', 'komi', 'tournament_code')`

New code: `
        fields = ("game_date", "round", "pin_player_1",
                "pin_player_2", 'handicap', 'komi')`

**Comment by vash3g** [comment]
GameTable class is called multiple times for this issue. Once for the main landing page which shows all rated game info and One for the individual player pages. To accurately change this per the request it would have to be replicated and changed for each call.

**Comment by EarthSchlange** [comment]
Resolved with pull request #53.
