### ISSUE TITLE
Tournament Display shows "Rated On" as "--" for all tournaments.

### ISSUE THREAD

**Issue by JonathanBresler** [usgo/agagd#23]
Recommend changing "Rated On" to "Rated ?" or "Rated Y/N".
Reason: just got results for Simsbury played on 2013-03-02.
Rated it on 2013-03-29.  All tournaments from that same date or lated where rerated as a result.  Should "Rated On" be the first time rated?, the last time rated? or the most recent time rated?

"Rated Y/N"  should be based upon 
"select distinct g.Tournament_Code from games g where g.Rated = 1;"

**Comment by vash3g** [comment]
Tables.py lists the following for the main code for what are the latest tournaments:
```
class TournamentTable(tables.Table):
    tournament_code = tables.LinkColumn(
            'agagd_core.views.tournament_detail',
            kwargs={'tourn_code':tables.A('tournament_code')},)
    elab_date = tables.Column(verbose_name="rated on")

    class Meta:
        model = Tournament
        attrs = {"class": "paleblue"}
        fields = ("tournament_code", "description", "tournament_date", "city", "state", "total_players", "rounds", 'elab_date')
        sequence = fields
```
The code is looking for the 'elab_date' code within the usgo_agagd.tournaments table. This field is has no values within that table and only lists as 0000-00-00.  This table also has no column for "rated".

The table that needs to be looked at is in usgo_agagd.games table is either the 'rated' field which is either 0/1. This table also updates the 'elab_date' table and has current dates for when it was rated on. 

The code for this table on the page will need to reference both the "tournaments" table and the "games" table as the information is different. "Tournaments" references the recent/full list of tournaments we have tracked. "Games" is the full list of individual games and when they have been played/results/players/rated information. Both tables reference 'tournament_code' column which can compare the tournament with the rated on information.

**Comment by vash3g** [comment]
This was resolved as for a PR listed here: https://github.com/usgo/AGA-Ratings-Program/pull/3

Tested and working on the test site. Merged into code.
