### ISSUE TITLE
 PowerBI rating drill down do not include all games

### ISSUE THREAD

**Issue by robertqi78** [usgo/agagd#261]
Hi, the drill down on the player card did not show all the games.  For example, Alexander Qi (23560) played 4 games against Eric Yoder (20753).  This is shown correctly on the right lower box.  However, on the top box where it should have shown 4 games, it only shows 3.  The game that is missing is from "proqual20220701".  In the existing agadb, all the games are there.

![image](https://user-images.githubusercontent.com/73952781/185701181-b0542f5f-8c99-4a94-adac-bec6056a60ab.png)

**Comment by gurujeet-ngc** [comment]
If two players played more than once in the same tournament, sometimes not all games were displayed. This has been fixed.
![image](https://user-images.githubusercontent.com/69980961/185806682-c3ba13da-83cd-4463-b023-cfc2c2ba4740.png)

**Comment by robertqi78** [comment]
great.  thanks

**Comment by robertqi78** [comment]
close issue
