### ISSUE TITLE
Do we want to match usgo.org style?

### ISSUE THREAD

**Issue by amj** [usgo/agagd#31]
should we match the usgo.org colors?

**Comment by vash3g** [comment]
Please use templates found in /vaw/www/usgo.org/theme. probably index.twocolumn.php for this site.

**Comment by EarthSchlange** [comment]
Are we still looking to match the agagd to usgo.org's theme? If we are not, can this issue be closed?

**Comment by EarthSchlange** [comment]
Closing. This is being resolved through a different processes and redesign.
