### ISSUE TITLE
How often is the AGAGD updated?

### ISSUE THREAD

**Issue by pconerly** [usgo/agagd#41]
I played in the Seattle monthly ratings tournament at the beginning of July and I was just wondering when  everything gets updated.  I noticed that the last updated tournament was on June 20.

Is this project responsible for calculating ratings, or is it just pulling in data from elsewhere?

**Comment by amj** [comment]
it pulls the ratings data from elsewhere; the ratings czar for the AGA can be reached at ratings@usgo.org -- he usually updates the ratings weekly, but sometimes it takes two weeks or more.

There are other reasons ratings can be delayed: Sometimes, tournament directors don't send their results files in until much later, sometimes they send invalid files, sometimes they send files with duplicate members, etc. etc.

Best bet is to e-mail the tournament director first to make sure they've submitted their ratings, and if so, then to ratings@ to find out what might be holding them up.

**Comment by pconerly** [comment]
Cool, thanks :japanese_castle:
