### ISSUE TITLE
Add 'most rated games' table to landing

### ISSUE THREAD

**Issue by amj** [usgo/agagd#44]
as it currently is on usgo.org/ratings

**Comment by EarthSchlange** [comment]
USGO Slack MSG - @vash3g 
> Can you update this issue with where Andrew **@amj** might find those lookups so we can add them to the AGAGD? Thanks! 

@amj I have added a new GitHub Repo for usgo [Top Ratings](github.com/usgo/top_ratings) which contains the scripts that control `/ratings` page; normally, `/var/www/usgo.org/ratings_ori` on the server. The lookup scrips are [RatingsLookUpByID.php][1] and [RatingLookupByName.php][2].

[1]: https://github.com/usgo/top_ratings/blob/master/RatingLookupByID.php
[2]: https://github.com/usgo/top_ratings/blob/master/RatingLookupByName.php

**Comment by vash3g** [comment]
For full sql query: https://github.com/usgo/top_ratings/blob/master/ratings_files/topDanKyu.php

**Comment by vash3g** [comment]
Added to the front page with PR #61
