### ISSUE TITLE
Add "most tournaments" table to landing page

### ISSUE THREAD

**Issue by amj** [usgo/agagd#46]
as it is on usgo.org/ratings

**Comment by vash3g** [comment]
USGO Slack MSG - @vash3g

> Can you update this issue with where Andrew **@amj** might find those lookups so we can add them to the AGAGD? Thanks!

@amj I have added a new GitHub Repo for usgo [Top Ratings](github.com/usgo/top_ratings) which contains the scripts that control `/ratings` page; normally, `/var/www/usgo.org/ratings_ori` on the server. The lookup scrips are [RatingsLookUpByID.php](https://github.com/usgo/top_ratings/blob/master/RatingLookupByID.php) and [RatingLookupByName.php](https://github.com/usgo/top_ratings/blob/master/RatingLookupByName.php).

for sql query: https://github.com/usgo/top_ratings/blob/master/ratings_files/topDanKyu.php

**Comment by EarthSchlange** [comment]
Related Issue: [**Add 'most rated games' table to landing**](https://github.com/usgo/agagd/issues/44) #44.

**Comment by vash3g** [comment]
List added with addition of PR #61
