### ISSUE TITLE
Create new view for 'Top 100 [Current] Members'

### ISSUE THREAD

**Issue by vash3g** [usgo/agagd#63]
https://www.usgo.org/all-players-rating displays all members in an orderly list for the top members. We have an easy top 10 list on the main page. This would be a larger list for those looking to see their placement among active/current members.

**Comment by EarthSchlange** [comment]
I think we could short list this on the main page to say 25 members. We could then add an top members view with a pager that would list 100 players.

How are the top members being sorted here i.e., activity or highest rating?

**Comment by EarthSchlange** [comment]
Fixed with #77, #78, #79 and #80 

![image](https://user-images.githubusercontent.com/5054653/84187403-d8cd7e80-aa46-11ea-99aa-03aab4eb0976.png)
