### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by annabunches** [usgo/agagd#69]
On loading https://agagd.usgo.org, there are several 404s:

https://agagd.usgo.org/static/img/header-bg.png
https://agagd.usgo.org/static/img/arrow-active-down.png
https://agagd.usgo.org/static/img/arrow-inactive-up.png
https://agagd.usgo.org/favicon.ico

favicon is pretty 'normal' to be missing, but these others seem to be referenced by templates but not provided. Not sure whether there's any real impact; potentially those missing arrow images are making some buttons invisible, I suppose.

**Comment by annabunches** [comment]
More information: during `manage.py collectstatic` on my local machine, I can see these files being copied. However, they end up in `/tmp/static/django_tables2/themes/paleblue/img`, but the code apparently just references `/tmp/static`.

**Comment by EarthSchlange** [comment]
There could be a potential impact with this as it seems to be a table sorting feature. I don't think those files were ever added to this repo. The initial css change: c451033a0a05a070e323485.

## Arrows Locally
![Screenshot_20200208_111342](https://user-images.githubusercontent.com/5054653/74091112-dd6a3200-4a68-11ea-8ba0-c096d192a47c.png)

I have asked @vash3g about a favicon for the agagd, and he told me a favicon would need to be created for the agagd.

**Comment by vash3g** [comment]
Since this is an AGA app we could use the AGA logo/favicon for the AGAGD. The icon is generally so small i dont think it would show up effectively unless you have an old old display.

**Comment by vash3g** [comment]
Pulled images from legacy server, sent to bad PR and Michael made a good PR and added them to the test server. they look gooood.
