### ISSUE TITLE
Fixes prior to removing /ratings pages

### ISSUE THREAD

**Issue by vash3g** [usgo/agagd#83]
On player search:
Add rating to search
Change "Chapters" to "Chapter"

General:
Update copyright to 2020

**Comment by vash3g** [comment]
Make Ratings show larger on member page.

**Comment by vash3g** [comment]
Top of members page needs to be in two columns. Member Demographics/last tournament info needs to be in one column and graph in another. When the page is viewed in a thin window the left text is badly adjusted on the page and can become unreadable. Example: 
![image](https://user-images.githubusercontent.com/994470/83992337-f7842600-a91d-11ea-8286-bee51ee19f2a.png)

**Comment by EarthSchlange** [comment]
## Update to members layout changes GIF
![Two Columns 2020-06-09 11-36](https://user-images.githubusercontent.com/5054653/84186638-ad965f80-aa45-11ea-8242-e2d98438912d.gif)

**Comment by vash3g** [comment]
Change "aga id" to "AGA ID" in search box

**Comment by vash3g** [comment]
Changes completed and more will be assigned as new issues. Page to swap 9/13 weekend.
